In [47]:
# Load in libraries and match data

import json
import pandas as pd

with open("Single Match Data.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

# Index to make sure we have correct order of events

df = df.sort_values("index").reset_index(drop=True)

In [48]:
df. head()

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,shot.one_on_one,foul_committed.advantage,foul_won.advantage,clearance.aerial_won,pass.deflected,pass.no_touch,foul_committed.type.id,foul_committed.type.name,pass.straight,pass.goal_assist
0,9f6e2ecf-6685-45df-a62e-c2db3090f6c1,1,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0300039d-150d-41e4-b29a-76602ef002e6,2,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,491e8901-7630-4cc8-b57b-937dddff2eaa,3,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,757b85ad-ddfe-44d5-b893-c23a9fb709d8,4,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,549567bd-36de-4ac8-b8dc-6b5d3f1e4be8,5,1,00:00:00.575,0,0,2,2.015669,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df["type.name"].value_counts()

type.name
Pass              1163
Ball Receipt*     1058
Carry              890
Pressure           212
Ball Recovery       89
Duel                53
Clearance           37
Goal Keeper         34
Block               32
Shot                28
Interception        24
Dribble             24
Foul Committed      23
Dispossessed        21
Foul Won            21
Miscontrol          17
Dribbled Past       14
Substitution         6
Half Start           4
Half End             4
Tactical Shift       4
Starting XI          2
Bad Behaviour        1
Error                1
Name: count, dtype: int64

In [50]:
# Don't want location like this [61.0, 40.1]

df["x"] = df["location"].apply(
    lambda loc: loc[0] if isinstance(loc, list) else None
)

df["y"] = df["location"].apply(
    lambda loc: loc[1] if isinstance(loc, list) else None
)

In [51]:
df["type.name"].value_counts()

type.name
Pass              1163
Ball Receipt*     1058
Carry              890
Pressure           212
Ball Recovery       89
Duel                53
Clearance           37
Goal Keeper         34
Block               32
Shot                28
Interception        24
Dribble             24
Foul Committed      23
Dispossessed        21
Foul Won            21
Miscontrol          17
Dribbled Past       14
Substitution         6
Half Start           4
Half End             4
Tactical Shift       4
Starting XI          2
Bad Behaviour        1
Error                1
Name: count, dtype: int64

In [52]:
df["possession"].nunique()

143

In [53]:
# See what shots look like for EDA

shots = df[df["type.name"] == "Shot"].copy()

shots[[
    "team.name",
    "player.name",
    "possession",
    "shot.statsbomb_xg",
    "shot.outcome.name"
]]

,team.name,player.name,possession,shot.statsbomb_xg,shot.outcome.name
136,Barcelona,Lionel Andrés Messi Cuccittini,6,0.076992,Off T
261,Barcelona,Jordi Alba Ramos,12,0.051668,Off T
714,Barcelona,Lionel Andrés Messi Cuccittini,23,0.016932,Saved
742,Deportivo Alavés,Rubén Sobrino Pozuelo,30,0.122604,Off T
801,Barcelona,Luis Alberto Suárez Díaz,33,0.041751,Off T
1340,Barcelona,Ousmane Dembélé,50,0.076063,Wayward
1546,Barcelona,Ivan Rakitić,58,0.112513,Off T
1587,Barcelona,Lionel Andrés Messi Cuccittini,61,0.049074,Post
1591,Barcelona,Gerard Piqué Bernabéu,61,0.115620,Off T
1619,Barcelona,Ousmane Dembélé,63,0.123355,Saved
1686,Barcelona,Luis Alberto Suárez Díaz,66,0.143263,Wayward
1788,Barcelona,Ousmane Dembélé,71,0.082343,Off T
1996,Barcelona,Jordi Alba Ramos,78,0.214252,Saved
2163,Deportivo Alavés,Mubarak Wakaso,82,0.028697,Blocked
2363,Barcelona,Luis Alberto Suárez Díaz,86,0.043025,Blocked
2395,Barcelona,Philippe Coutinho Correia,87,0.021350,Blocked
2432,Barcelona,Jordi Alba Ramos,87,0.055740,Blocked
2504,Barcelona,Lionel Andrés Messi Cuccittini,90,0.024774,Off T
2626,Barcelona,Philippe Coutinho Correia,96,0.026191,Blocked
2720,Barcelona,Lionel Andrés Messi Cuccittini,97,0.083203,Goal
2789,Barcelona,Lionel Andrés Messi Cuccittini,99,0.069851,Post
2900,Barcelona,Ivan Rakitić,103,0.015055,Wayward
3021,Barcelona,Luis Alberto Suárez Díaz,110,0.261578,Saved
3186,Deportivo Alavés,Adrián Marín Gómez,122,0.140808,Off T
3343,Barcelona,Philippe Coutinho Correia,128,0.334535,Saved
3385,Barcelona,Philippe Coutinho Correia,130,0.105343,Goal
3641,Barcelona,Lionel Andrés Messi Cuccittini,138,0.094830,Saved
3758,Barcelona,Lionel Andrés Messi Cuccittini,143,0.420624,Goal

In [ ]:
#Extract columns we want

cols = [
    "possession",
    "team.name",
    "player.name",
    "type.name",
    "x",
    "y",
    "shot.statsbomb_xg",
    "shot.outcome.name"
]

# Take out usesless values

df = df[
    ~df["type.name"].isin(["Half Start", "Starting XI"])
].copy()

# Half Start and Starting XI counted as possession 1 (which we have now taken out). We want to make the first true possession = 1 

df["possession"] = df["possession"] - 1

,possession,team.name,player.name,type.name,x,y,shot.statsbomb_xg,shot.outcome.name
4,1,Deportivo Alavés,Jonathan Rodríguez Menéndez,Pass,61.0,40.1,NaN,NaN
5,1,Deportivo Alavés,Guillermo Alfonso Maripán Loaysa,Ball Receipt*,33.8,28.0,NaN,NaN
6,1,Deportivo Alavés,Guillermo Alfonso Maripán Loaysa,Carry,33.8,28.0,NaN,NaN
7,1,Deportivo Alavés,Guillermo Alfonso Maripán Loaysa,Pass,36.8,27.3,NaN,NaN
8,1,Deportivo Alavés,Rubén Sobrino Pozuelo,Ball Receipt*,79.8,75.9,NaN,NaN
...,...,...,...,...,...,...,...,...
79,4,Barcelona,Ivan Rakitić,Pass,69.6,12.8,NaN,NaN
80,4,Barcelona,Sergio Busquets i Burgos,Ball Receipt*,77.5,24.1,NaN,NaN
81,4,Barcelona,Sergio Busquets i Burgos,Carry,77.5,24.1,NaN,NaN
82,4,Barcelona,Sergio Busquets i Burgos,Pass,78.1,26.9,NaN,NaN
83,4,Barcelona,Samuel Yves Umtiti,Ball Receipt*,64.4,27.5,NaN,NaN

In [55]:
with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None
):
    display(df[cols]).head(80)

      possession         team.name                             player.name  \
4              1  Deportivo Alavés             Jonathan Rodríguez Menéndez
5              1  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
6              1  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
7              1  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
8              1  Deportivo Alavés                   Rubén Sobrino Pozuelo
9              1  Deportivo Alavés                   Rubén Sobrino Pozuelo
10             2         Barcelona                Sergio Busquets i Burgos
11             2         Barcelona                            Ivan Rakitić
12             2         Barcelona                            Ivan Rakitić
13             2         Barcelona                         Ousmane Dembélé
14             2         Barcelona                         Ousmane Dembélé
15             2         Barcelona                         Ousmane Dembélé
16             2         Barcelona                        Jordi Alba Ramos
17             2         Barcelona                        Jordi Alba Ramos
18             2  Deportivo Alavés               Víctor Laguardia Cisneros
19             2  Deportivo Alavés               Víctor Laguardia Cisneros
20             2  Deportivo Alavés               Víctor Laguardia Cisneros
21             2         Barcelona                   Marc-André ter Stegen
22             2         Barcelona                   Marc-André ter Stegen
23             2         Barcelona                   Marc-André ter Stegen
24             2         Barcelona                   Gerard Piqué Bernabéu
25             2         Barcelona                   Gerard Piqué Bernabéu
26             2         Barcelona                   Gerard Piqué Bernabéu
27             2         Barcelona                    Nélson Cabral Semedo
28             2         Barcelona                    Nélson Cabral Semedo
29             2         Barcelona                    Nélson Cabral Semedo
30             2         Barcelona                  Sergi Roberto Carnicer
31             2         Barcelona                  Sergi Roberto Carnicer
32             2         Barcelona                  Sergi Roberto Carnicer
33             2         Barcelona                    Nélson Cabral Semedo
34             2         Barcelona                    Nélson Cabral Semedo
35             2         Barcelona                    Nélson Cabral Semedo
36             2         Barcelona                      Samuel Yves Umtiti
37             2         Barcelona                      Samuel Yves Umtiti
38             2         Barcelona                      Samuel Yves Umtiti
39             2         Barcelona                        Jordi Alba Ramos
40             2         Barcelona                        Jordi Alba Ramos
41             2         Barcelona                        Jordi Alba Ramos
42             2         Barcelona                            Ivan Rakitić
43             2         Barcelona                            Ivan Rakitić
44             2         Barcelona                            Ivan Rakitić
45             2         Barcelona                   Gerard Piqué Bernabéu
46             2         Barcelona                   Gerard Piqué Bernabéu
47             2         Barcelona                   Gerard Piqué Bernabéu
48             2         Barcelona                      Samuel Yves Umtiti
49             2         Barcelona                      Samuel Yves Umtiti
50             2         Barcelona                      Samuel Yves Umtiti
51             2         Barcelona                   Gerard Piqué Bernabéu
52             2         Barcelona                   Gerard Piqué Bernabéu
53             2         Barcelona                   Gerard Piqué Bernabéu
54             2         Barcelona          Lionel Andrés Messi Cuccittini
55             2         Barcelona          Lionel Andrés Messi Cuccittini
56             2         Barcelona          Lionel Andrés Messi Cuccittini
57             2         Barcelona                  Sergi Roberto Carnicer
58             3  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
59             3  Deportivo Alavés                    Rubén Duarte Sánchez
60             3  Deportivo Alavés                    Rubén Duarte Sánchez
61             3         Barcelona                  Sergi Roberto Carnicer
62             3  Deportivo Alavés                    Rubén Duarte Sánchez
63             3  Deportivo Alavés             Jonathan Rodríguez Menéndez
64             3  Deportivo Alavés             Jonathan Rodríguez Menéndez
65             3  Deportivo Alavés             Jonathan Rodríguez Menéndez
66             3         Barcelona                    Nélson Cabral Semedo
67             4         Barcelona                Sergio Busquets i Burgos
68             4         Barcelona                      Samuel Yves Umtiti
69             4         Barcelona                      Samuel Yves Umtiti
70             4         Barcelona                      Samuel Yves Umtiti
71             4         Barcelona                        Jordi Alba Ramos
72             4         Barcelona                        Jordi Alba Ramos
73             4         Barcelona                        Jordi Alba Ramos
74             4         Barcelona                         Ousmane Dembélé
75             4         Barcelona                         Ousmane Dembélé
76             4         Barcelona                         Ousmane Dembélé
77             4         Barcelona                            Ivan Rakitić
78             4         Barcelona                            Ivan Rakitić
79             4         Barcelona                            Ivan Rakitić
80             4         Barcelona                Sergio Busquets i Burgos
81             4         Barcelona                Sergio Busquets i Burgos
82             4         Barcelona                Sergio Busquets i Burgos
83             4         Barcelona                      Samuel Yves Umtiti
84             4         Barcelona                      Samuel Yves Umtiti
85             4         Barcelona                      Samuel Yves Umtiti
86             4         Barcelona                            Ivan Rakitić
87             4         Barcelona                            Ivan Rakitić
88             4         Barcelona                            Ivan Rakitić
89             4         Barcelona                        Jordi Alba Ramos
90             4         Barcelona                        Jordi Alba Ramos
91             4  Deportivo Alavés           Martín Aguirregabiria Padilla
92             5         Barcelona                        Jordi Alba Ramos
93             5         Barcelona                            Ivan Rakitić
94             5         Barcelona                            Ivan Rakitić
95             5         Barcelona                   Gerard Piqué Bernabéu
96             5         Barcelona                   Gerard Piqué Bernabéu
97             5         Barcelona                   Gerard Piqué Bernabéu
98             5         Barcelona                    Nélson Cabral Semedo
99             5         Barcelona                    Nélson Cabral Semedo
100            5         Barcelona                    Nélson Cabral Semedo
101            5         Barcelona          Lionel Andrés Messi Cuccittini
102            5         Barcelona          Lionel Andrés Messi Cuccittini
103            5         Barcelona                    Nélson Cabral Semedo
104            5         Barcelona                    Nélson Cabral Semedo
105            5  Deportivo Alavés             Jonathan Rodríguez Menéndez
106            5         Barcelona                    Nélson Cabral Semedo
107            5         Barcelona                  Sergi Roberto Carnicer
108            5         Barcelona                  Sergi Roberto Carnicer
109            5         Barcelona          Lionel Andrés Messi Cuccittini
110            5         Barcelona          Lionel Andrés Messi Cuccittini
111            5         Barcelona          Lionel Andrés Messi Cuccittini
112            5         Barcelona                      Samuel Yves Umtiti
113            5         Barcelona                      Samuel Yves Umtiti
114            5         Barcelona                      Samuel Yves Umtiti
115            5         Barcelona                            Ivan Rakitić
116            5  Deportivo Alavés                          Mubarak Wakaso
117            5  Deportivo Alavés                   Rubén Sobrino Pozuelo
118            5         Barcelona                Sergio Busquets i Burgos
119            5         Barcelona                            Ivan Rakitić
120            5  Deportivo Alavés                        Ibai Gómez Pérez
121            5         Barcelona                  Sergi Roberto Carnicer
122            5  Deportivo Alavés                          Mubarak Wakaso
123            5  Deportivo Alavés                          Mubarak Wakaso
124            5  Deportivo Alavés                        Ibai Gómez Pérez
125            5         Barcelona                        Jordi Alba Ramos
126            5         Barcelona                   Marc-André ter Stegen
127            5         Barcelona                   Marc-André ter Stegen
128            5         Barcelona                   Gerard Piqué Bernabéu
129            5         Barcelona                   Gerard Piqué Bernabéu
130            5         Barcelona                   Gerard Piqué Bernabéu
131            5         Barcelona                            Ivan Rakitić
132            5         Barcelona                            Ivan Rakitić
133            5         Barcelona                            Ivan Rakitić
134            5         Barcelona          Lionel Andrés Messi Cuccittini
135            5  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
136            5         Barcelona          Lionel Andrés Messi Cuccittini
137            5  Deportivo Alavés                 Fernando Pacheco Flores
138            6  Deportivo Alavés                 Fernando Pacheco Flores
139            7         Barcelona                        Jordi Alba Ramos
140            7         Barcelona                Sergio Busquets i Burgos
141            7         Barcelona                Sergio Busquets i Burgos
142            7         Barcelona                    Nélson Cabral Semedo
143            7         Barcelona                    Nélson Cabral Semedo
144            7         Barcelona                    Nélson Cabral Semedo
145            7         Barcelona                  Sergi Roberto Carnicer
146            7         Barcelona                  Sergi Roberto Carnicer
147            7  Deportivo Alavés         Manuel Alejandro García Sánchez
148            7         Barcelona                  Sergi Roberto Carnicer
149            7         Barcelona          Lionel Andrés Messi Cuccittini
150            7  Deportivo Alavés         Manuel Alejandro García Sánchez
151            7         Barcelona                Sergio Busquets i Burgos
152            7         Barcelona                Sergio Busquets i Burgos
153            7         Barcelona                Sergio Busquets i Burgos
154            7         Barcelona                   Gerard Piqué Bernabéu
155            7         Barcelona                   Gerard Piqué Bernabéu
156            7         Barcelona                   Gerard Piqué Bernabéu
157            7         Barcelona                      Samuel Yves Umtiti
158            7         Barcelona                      Samuel Yves Umtiti
159            7         Barcelona                      Samuel Yves Umtiti
160            7         Barcelona                        Jordi Alba Ramos
161            7         Barcelona                        Jordi Alba Ramos
162            7         Barcelona                        Jordi Alba Ramos
163            7         Barcelona                         Ousmane Dembélé
164            7         Barcelona                         Ousmane Dembélé
165            7         Barcelona                        Jordi Alba Ramos
166            7         Barcelona                        Jordi Alba Ramos
167            7         Barcelona                        Jordi Alba Ramos
168            7         Barcelona                            Ivan Rakitić
169            7         Barcelona                            Ivan Rakitić
170            7         Barcelona                            Ivan Rakitić
171            7         Barcelona                   Gerard Piqué Bernabéu
172            7         Barcelona                   Gerard Piqué Bernabéu
173            7         Barcelona                   Gerard Piqué Bernabéu
174            7         Barcelona                        Jordi Alba Ramos
175            7         Barcelona                        Jordi Alba Ramos
176            7         Barcelona                        Jordi Alba Ramos
177            7         Barcelona                         Ousmane Dembélé
178            7         Barcelona                         Ousmane Dembélé
179            7         Barcelona                         Ousmane Dembélé
180            7         Barcelona                  Sergi Roberto Carnicer
181            7  Deportivo Alavés             Jonathan Rodríguez Menéndez
182            7         Barcelona                  Sergi Roberto Carnicer
183            7         Barcelona                    Nélson Cabral Semedo
184            7         Barcelona                    Nélson Cabral Semedo
185            7         Barcelona                    Nélson Cabral Semedo
186            7         Barcelona                  Sergi Roberto Carnicer
187            7         Barcelona                  Sergi Roberto Carnicer
188            7         Barcelona                  Sergi Roberto Carnicer
189            7         Barcelona                Sergio Busquets i Burgos
190            7         Barcelona                Sergio Busquets i Burgos
191            7         Barcelona                  Sergi Roberto Carnicer
192            7         Barcelona                  Sergi Roberto Carnicer
193            7         Barcelona                  Sergi Roberto Carnicer
194            7  Deportivo Alavés         Manuel Alejandro García Sánchez
195            7         Barcelona                  Sergi Roberto Carnicer
196            8  Deportivo Alavés         Manuel Alejandro García Sánchez
197            8  Deportivo Alavés                   Rubén Sobrino Pozuelo
198            8  Deportivo Alavés                   Rubén Sobrino Pozuelo
199            8  Deportivo Alavés                   Rubén Sobrino Pozuelo
200            8  Deportivo Alavés             Jonathan Rodríguez Menéndez
201            8  Deportivo Alavés             Jonathan Rodríguez Menéndez
202            8  Deportivo Alavés             Jonathan Rodríguez Menéndez
203            8  Deportivo Alavés                   Rubén Sobrino Pozuelo
204            9         Barcelona                   Marc-André ter Stegen
205            9         Barcelona                   Marc-André ter Stegen
206            9         Barcelona                        Jordi Alba Ramos
207            9         Barcelona                        Jordi Alba Ramos
208            9         Barcelona                         Ousmane Dembélé
209            9         Barcelona                         Ousmane Dembélé
210            9         Barcelona                         Ousmane Dembélé
211            9         Barcelona                            Ivan Rakitić
212            9         Barcelona                            Ivan Rakitić
213            9         Barcelona                            Ivan Rakitić
214            9         Barcelona                         Ousmane Dembélé
215            9         Barcelona                         Ousmane Dembélé
216            9         Barcelona                         Ousmane Dembélé
217            9         Barcelona                Luis Alberto Suárez Díaz
218            9         Barcelona                Luis Alberto Suárez Díaz
219            9         Barcelona                Luis Alberto Suárez Díaz
220            9         Barcelona                            Ivan Rakitić
221            9         Barcelona                            Ivan Rakitić
222            9         Barcelona                  Sergi Roberto Carnicer
223            9         Barcelona                  Sergi Roberto Carnicer
224            9         Barcelona                  Sergi Roberto Carnicer
225            9         Barcelona                Luis Alberto Suárez Díaz
226           10  Deportivo Alavés                 Fernando Pacheco Flores
227           10  Deportivo Alavés                   Rubén Sobrino Pozuelo
228           11         Barcelona                   Gerard Piqué Bernabéu
229           11         Barcelona                   Marc-André ter Stegen
230           11         Barcelona                   Marc-André ter Stegen
231           11         Barcelona                   Marc-André ter Stegen
232           11         Barcelona                   Gerard Piqué Bernabéu
233           11         Barcelona                   Gerard Piqué Bernabéu
234           11         Barcelona                   Gerard Piqué Bernabéu
235           11         Barcelona                Sergio Busquets i Burgos
236           11         Barcelona                Sergio Busquets i Burgos
237           11  Deportivo Alavés         Manuel Alejandro García Sánchez
238           11         Barcelona                Sergio Busquets i Burgos
239           11         Barcelona                    Nélson Cabral Semedo
240           11         Barcelona                    Nélson Cabral Semedo
241           11         Barcelona                    Nélson Cabral Semedo
242           11         Barcelona                Sergio Busquets i Burgos
243           11         Barcelona                Sergio Busquets i Burgos
244           11         Barcelona                Sergio Busquets i Burgos
245           11         Barcelona                         Ousmane Dembélé
246           11         Barcelona                         Ousmane Dembélé
247           11         Barcelona                         Ousmane Dembélé
248           11         Barcelona                            Ivan Rakitić
249           11         Barcelona                            Ivan Rakitić
250           11         Barcelona                            Ivan Rakitić
251           11         Barcelona          Lionel Andrés Messi Cuccittini
252           11  Deportivo Alavés                    Rubén Duarte Sánchez
253           11  Deportivo Alavés             Jonathan Rodríguez Menéndez
254           11  Deportivo Alavés             Jonathan Rodríguez Menéndez
255           11         Barcelona                  Sergi Roberto Carnicer
256           11  Deportivo Alavés             Jonathan Rodríguez Menéndez
257           11         Barcelona          Lionel Andrés Messi Cuccittini
258           11         Barcelona          Lionel Andrés Messi Cuccittini
259           11         Barcelona          Lionel Andrés Messi Cuccittini
260           11         Barcelona                        Jordi Alba Ramos
261           11         Barcelona                        Jordi Alba Ramos
262           11  Deportivo Alavés                 Fernando Pacheco Flores
263           12  Deportivo Alavés                 Fernando Pacheco Flores
264           12  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
265           12  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
266           12  Deportivo Alavés        Guillermo Alfonso Maripán Loaysa
267           12  Deportivo Alavés                   Rubén Sobrino Pozuelo
268           12         Barcelona                   Gerard Piqué Bernabéu

AttributeError: 'NoneType' object has no attribute 'head'